name: Generate Static Files

on:
  push:
    branches:
      - main
    paths:
      - "raw_data/**"
      - "transform.py"

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run data generator
        run: |
          python transform.py ./raw_data

      - name: Deploy generated files
        uses: JamesIves/github-pages-deploy-action@4.1.0
        with:
          branch: gh-pages
          folder: out
          single-commit: true
